server:
  port: 8070

eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8070}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"